=begin


OpenAPI spec version: 

Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::PostitDeleteApiKey
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'PostitDeleteApiKey' do
  before do
    # run before each test
    @instance = SwaggerClient::PostitDeleteApiKey.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PostitDeleteApiKey' do
    it 'should create an instact of PostitDeleteApiKey' do
      @instance.should be_a(SwaggerClient::PostitDeleteApiKey) 
    end
  end
  describe 'test attribute "api_key"' do
    it 'should work' do
       # assertion here
       # should be_a()
       # should be_nil
       # should ==
       # should_not ==
    end
  end

end

