=begin


OpenAPI spec version: 

Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::PostitUpdatePostItTableResponse
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'PostitUpdatePostItTableResponse' do
  before do
    # run before each test
    @instance = SwaggerClient::PostitUpdatePostItTableResponse.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PostitUpdatePostItTableResponse' do
    it 'should create an instact of PostitUpdatePostItTableResponse' do
      @instance.should be_a(SwaggerClient::PostitUpdatePostItTableResponse) 
    end
  end
end

