=begin


OpenAPI spec version: 

Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::PostitPostItResponse
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'PostitPostItResponse' do
  before do
    # run before each test
    @instance = SwaggerClient::PostitPostItResponse.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PostitPostItResponse' do
    it 'should create an instact of PostitPostItResponse' do
      @instance.should be_a(SwaggerClient::PostitPostItResponse) 
    end
  end
end

