#
# Copyright 2016 SmartBear Software
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#
# NOTE: This class is auto generated by Swagger Codegen
# Please update the test case below to test the API endpoints.
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::SwaggerClient::PostItServiceApi');

my $api = WWW::SwaggerClient::PostItServiceApi->new();
isa_ok($api, 'WWW::SwaggerClient::PostItServiceApi');

#
# create_post_it_table test
#
{
    my $body = undef; # replace NULL with a proper value
    my $result = $api->create_post_it_table(body => $body);
}

#
# delete_api_key test
#
{
    my $body = undef; # replace NULL with a proper value
    my $result = $api->delete_api_key(body => $body);
}

#
# post_it test
#
{
    my $body = undef; # replace NULL with a proper value
    my $result = $api->post_it(body => $body);
}

#
# regenerate_api_key test
#
{
    my $body = undef; # replace NULL with a proper value
    my $result = $api->regenerate_api_key(body => $body);
}

#
# update_post_it_table test
#
{
    my $body = undef; # replace NULL with a proper value
    my $result = $api->update_post_it_table(body => $body);
}


1;
