//
// PostitUpdatePostItTable.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class PostitUpdatePostItTable: JSONEncodable {

    public var apiKey: String?
    public var path: String?
    public var schema: String?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["api_key"] = self.apiKey
        nillableDictionary["path"] = self.path
        nillableDictionary["schema"] = self.schema
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
