//
// PostitCreatePostItTable.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class PostitCreatePostItTable: JSONEncodable {

    public var path: String?
    public var schema: String?
    public var shardName: String?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["path"] = self.path
        nillableDictionary["schema"] = self.schema
        nillableDictionary["shard_name"] = self.shardName
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
