//
// PostitPostIt.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class PostitPostIt: JSONEncodable {

    public var apiKey: String?
    public var eventTime: Int?
    public var payload: String?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["api_key"] = self.apiKey
        nillableDictionary["event_time"] = self.eventTime
        nillableDictionary["payload"] = self.payload
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
