#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGPostitCreatePostItTable
@end

@interface SWGPostitCreatePostItTable : SWGObject


@property(nonatomic) NSString* path;

@property(nonatomic) NSString* schema;

@property(nonatomic) NSString* shardName;

@end
