#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGPostitPostIt
@end

@interface SWGPostitPostIt : SWGObject


@property(nonatomic) NSString* apiKey;

@property(nonatomic) NSNumber* eventTime;

@property(nonatomic) NSString* payload;

@end
