#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGPostitUpdatePostItTable
@end

@interface SWGPostitUpdatePostItTable : SWGObject


@property(nonatomic) NSString* apiKey;

@property(nonatomic) NSString* path;

@property(nonatomic) NSString* schema;

@end
