#import <Foundation/Foundation.h>
#import "SWGPostitCreatePostItTableResponse.h"
#import "SWGPostitCreatePostItTable.h"
#import "SWGPostitDeleteApiKeyResponse.h"
#import "SWGPostitDeleteApiKey.h"
#import "SWGPostitPostItResponse.h"
#import "SWGPostitPostIt.h"
#import "SWGPostitRegenerateApiKeyResponse.h"
#import "SWGPostitRegenerateApiKey.h"
#import "SWGPostitUpdatePostItTableResponse.h"
#import "SWGPostitUpdatePostItTable.h"
#import "SWGObject.h"
#import "SWGApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface SWGPostItServiceApi: NSObject

@property(nonatomic, assign)SWGApiClient *apiClient;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(SWGPostItServiceApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(SWGPostItServiceApi*) sharedAPI;
///
///
/// PostItService.createPostItTable
/// 
///
/// @param body 
/// 
///
/// @return SWGPostitCreatePostItTableResponse*
-(NSNumber*) createPostItTableWithBody: (SWGPostitCreatePostItTable*) body
    completionHandler: (void (^)(SWGPostitCreatePostItTableResponse* output, NSError* error)) handler;


///
///
/// PostItService.deleteApiKey
/// 
///
/// @param body 
/// 
///
/// @return SWGPostitDeleteApiKeyResponse*
-(NSNumber*) deleteApiKeyWithBody: (SWGPostitDeleteApiKey*) body
    completionHandler: (void (^)(SWGPostitDeleteApiKeyResponse* output, NSError* error)) handler;


///
///
/// PostItService.postIt
/// 
///
/// @param body 
/// 
///
/// @return SWGPostitPostItResponse*
-(NSNumber*) postItWithBody: (SWGPostitPostIt*) body
    completionHandler: (void (^)(SWGPostitPostItResponse* output, NSError* error)) handler;


///
///
/// PostItService.regenerateApiKey
/// 
///
/// @param body 
/// 
///
/// @return SWGPostitRegenerateApiKeyResponse*
-(NSNumber*) regenerateApiKeyWithBody: (SWGPostitRegenerateApiKey*) body
    completionHandler: (void (^)(SWGPostitRegenerateApiKeyResponse* output, NSError* error)) handler;


///
///
/// PostItService.updatePostItTable
/// 
///
/// @param body 
/// 
///
/// @return SWGPostitUpdatePostItTableResponse*
-(NSNumber*) updatePostItTableWithBody: (SWGPostitUpdatePostItTable*) body
    completionHandler: (void (^)(SWGPostitUpdatePostItTableResponse* output, NSError* error)) handler;



@end
