using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing PostitRegenerateApiKeyResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PostitRegenerateApiKeyResponseTests
    {
        private PostitRegenerateApiKeyResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new PostitRegenerateApiKeyResponse();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of PostitRegenerateApiKeyResponse
        /// </summary>
        [Test]
        public void PostitRegenerateApiKeyResponseInstanceTest()
        {
            Assert.IsInstanceOf<PostitRegenerateApiKeyResponse> (instance, "instance is a PostitRegenerateApiKeyResponse");
        }

        
        /// <summary>
        /// Test the property 'ApiKey' 
        /// </summary>
        [Test]
        public void ApiKeyTest()
        {
            // TODO: unit test for the property 'ApiKey' 
        }
        

    }

}
