using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing PostitUpdatePostItTable
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PostitUpdatePostItTableTests
    {
        private PostitUpdatePostItTable instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new PostitUpdatePostItTable();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of PostitUpdatePostItTable
        /// </summary>
        [Test]
        public void PostitUpdatePostItTableInstanceTest()
        {
            Assert.IsInstanceOf<PostitUpdatePostItTable> (instance, "instance is a PostitUpdatePostItTable");
        }

        
        /// <summary>
        /// Test the property 'ApiKey' 
        /// </summary>
        [Test]
        public void ApiKeyTest()
        {
            // TODO: unit test for the property 'ApiKey' 
        }
        
        /// <summary>
        /// Test the property 'Path' 
        /// </summary>
        [Test]
        public void PathTest()
        {
            // TODO: unit test for the property 'Path' 
        }
        
        /// <summary>
        /// Test the property 'Schema' 
        /// </summary>
        [Test]
        public void SchemaTest()
        {
            // TODO: unit test for the property 'Schema' 
        }
        

    }

}
