using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing PostitUpdatePostItTableResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PostitUpdatePostItTableResponseTests
    {
        private PostitUpdatePostItTableResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new PostitUpdatePostItTableResponse();
        }
    
        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }   

        /// <summary>
        /// Test an instance of PostitUpdatePostItTableResponse
        /// </summary>
        [Test]
        public void PostitUpdatePostItTableResponseInstanceTest()
        {
            Assert.IsInstanceOf<PostitUpdatePostItTableResponse> (instance, "instance is a PostitUpdatePostItTableResponse");
        }

        

    }

}
